.PHONY: box_id_test

run:
	clang++ -g part1.cc -o part1 && \
	./part1 input.txt

run-p2:
	clang++ -g part2.cc -o part2 && \
	./part2 input.txt

box_id_test:
	clang++ -g box_id_test.cc -o box_id_test && \
	./box_id_test
